[project]
name = "compiladores-2026-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "antlr4-python3-runtime==4.13.2",
]

[dependency-groups]
dev = [
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
# --- TUTORIAL ---
"build:tutorial" = "cd tutorial && java -jar ../antlr-4.13.2-complete.jar -Dlanguage=Python3 Tutorial.g4"
"start:tutorial" = "cd tutorial && python main.py"

# --- TRABALHO 1: URLs ---
"build:url" = "cd analisador_urls && java -jar ../antlr-4.13.2-complete.jar -Dlanguage=Python3 UrlLexer.g4"
"start:url" = "cd analisador_urls && python main.py"

# --- TRABALHO 2: miniC ---
"build:minic" = "cd compilador_minic && java -jar ../antlr-4.13.2-complete.jar -Dlanguage=Python3 MiniC.g4"
"start:minic" = "cd compilador_minic && python main.py"

# --- TRABALHO 3: Avaliador de Expressões (LISTENER) ---
"build:expressao-listener" = "cd avaliador_expressoes_listener && java -jar ../antlr-4.13.2-complete.jar -Dlanguage=Python3 Expressao.g4"
"start:expressao-listener" = "cd avaliador_expressoes_listener && python main.py"

# --- TRABALHO 4: Avaliador de Expressões (VISITOR) ---
"build:expressao-visitor" = "cd avaliador_expressoes_visitor && java -jar ../antlr-4.13.2-complete.jar -Dlanguage=Python3 -visitor Expressao.g4"
"start:expressao-visitor" = "cd avaliador_expressoes_visitor && python main.py"

# --- TRABALHO 5: Geração de páginas HTML ---
"build:html" = "cd gerador_html && java -jar ../antlr-4.13.2-complete.jar -Dlanguage=Python3 -visitor Html.g4"
"start:html" = "cd gerador_html && python main.py entrada.txt"


# --- TRABALHO 6: Verificação de Variáveis, Tipos e Funções (miniC) ---
"build:minic-semantico" = "cd analisador_semantico_minic && java -jar ../antlr-4.13.2-complete.jar -Dlanguage=Python3 -visitor MiniC.g4"
"start:minic-semantico" = "cd analisador_semantico_minic && python main.py"